<?php

/**
 * InstallmentPlan
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sezzle API
 *
 * The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Sezzle;

/**
 * InstallmentPlan Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstallmentPlan
{
    /**
     * Possible values of this enum
     */
    private const _4_PAY_BIWEEKLY = '4-pay-biweekly';

    private const _4_PAY_MONTHLY = '4-pay-monthly';

    private const _6_PAY_MONTHLY = '6-pay-monthly';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_4_PAY_BIWEEKLY,
            self::_4_PAY_MONTHLY,
            self::_6_PAY_MONTHLY,
        ];
    }
}
