<?php

/**
 * OrderApi
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sezzle API
 *
 * The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Sezzle;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * OrderApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderApi
{
    protected \GuzzleHttp\ClientInterface $client;

    protected \OpenAPI\Client\Configuration $config;

    protected \OpenAPI\Client\HeaderSelector $headerSelector;

    /**
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $configuration = null,
        HeaderSelector $headerSelector = null,
        protected $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $configuration ?: new Configuration();
        $this->headerSelector = $headerSelector ?: new HeaderSelector();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    public function getConfig(): \OpenAPI\Client\Configuration
    {
        return $this->config;
    }

    /**
     * Operation deleteV2DeleteCheckoutByOrder
     *
     * Delete checkout by order
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function deleteV2DeleteCheckoutByOrder($order_uuid): void
    {
        $this->deleteV2DeleteCheckoutByOrderWithHttpInfo($order_uuid);
    }

    /**
     * Operation deleteV2DeleteCheckoutByOrderWithHttpInfo
     *
     * Delete checkout by order
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteV2DeleteCheckoutByOrderWithHttpInfo($order_uuid): array
    {
        $request = $this->deleteV2DeleteCheckoutByOrderRequest($order_uuid);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation deleteV2DeleteCheckoutByOrderAsync
     *
     * Delete checkout by order
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function deleteV2DeleteCheckoutByOrderAsync($order_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->deleteV2DeleteCheckoutByOrderAsyncWithHttpInfo($order_uuid)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation deleteV2DeleteCheckoutByOrderAsyncWithHttpInfo
     *
     * Delete checkout by order
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function deleteV2DeleteCheckoutByOrderAsyncWithHttpInfo($order_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        $request = $this->deleteV2DeleteCheckoutByOrderRequest($order_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                fn ($response): array => [null, $response->getStatusCode(), $response->getHeaders()],
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteV2DeleteCheckoutByOrder'
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function deleteV2DeleteCheckoutByOrderRequest($order_uuid): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling deleteV2DeleteCheckoutByOrder'
            );
        }

        $resourcePath = '/order/{order_uuid}/checkout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getV2Order
     *
     * Get order details
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return SessionStatus|object[]|object[]
     */
    public function getV2Order($order_uuid)
    {
        [$response] = $this->getV2OrderWithHttpInfo($order_uuid);

        return $response;
    }

    /**
     * Operation getV2OrderWithHttpInfo
     *
     * Get order details
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of SessionStatus|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getV2OrderWithHttpInfo($order_uuid)
    {
        $request = $this->getV2OrderRequest($order_uuid);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('SessionStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\SessionStatus::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                case 404:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\SessionStatus::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\SessionStatus::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 401:
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation getV2OrderAsync
     *
     * Get order details
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getV2OrderAsync($order_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->getV2OrderAsyncWithHttpInfo($order_uuid)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation getV2OrderAsyncWithHttpInfo
     *
     * Get order details
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getV2OrderAsyncWithHttpInfo($order_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\SessionStatus::class;
        $request = $this->getV2OrderRequest($order_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getV2Order'
     *
     * @param  string $order_uuid Order UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getV2OrderRequest($order_uuid): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling getV2Order'
            );
        }

        $resourcePath = '/order/{order_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchV2Checkout
     *
     * Update order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  \OpenAPI\Client\Sezzle\InlineObject1 $inline_object1 inline_object1 (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function patchV2Checkout($order_uuid, $inline_object1): void
    {
        $this->patchV2CheckoutWithHttpInfo($order_uuid, $inline_object1);
    }

    /**
     * Operation patchV2CheckoutWithHttpInfo
     *
     * Update order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  \OpenAPI\Client\Sezzle\InlineObject1 $inline_object1 (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchV2CheckoutWithHttpInfo($order_uuid, $inline_object1): array
    {
        $request = $this->patchV2CheckoutRequest($order_uuid, $inline_object1);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation patchV2CheckoutAsync
     *
     * Update order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  \OpenAPI\Client\Sezzle\InlineObject1 $inline_object1 (required)
     *
     * @throws \InvalidArgumentException
     */
    public function patchV2CheckoutAsync($order_uuid, $inline_object1): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->patchV2CheckoutAsyncWithHttpInfo($order_uuid, $inline_object1)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation patchV2CheckoutAsyncWithHttpInfo
     *
     * Update order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  \OpenAPI\Client\Sezzle\InlineObject1 $inline_object1 (required)
     *
     * @throws \InvalidArgumentException
     */
    public function patchV2CheckoutAsyncWithHttpInfo($order_uuid, $inline_object1): \GuzzleHttp\Promise\PromiseInterface
    {
        $request = $this->patchV2CheckoutRequest($order_uuid, $inline_object1);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                fn ($response): array => [null, $response->getStatusCode(), $response->getHeaders()],
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchV2Checkout'
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  \OpenAPI\Client\Sezzle\InlineObject1 $inline_object1 (required)
     *
     * @throws \InvalidArgumentException
     */
    public function patchV2CheckoutRequest($order_uuid, $inline_object1): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling patchV2Checkout'
            );
        }

        // verify the required parameter 'inline_object1' is set
        if ($inline_object1 === null || (is_array($inline_object1) && $inline_object1 === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $inline_object1 when calling patchV2Checkout'
            );
        }

        $resourcePath = '/order/{order_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($inline_object1)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($inline_object1));
            } else {
                $httpBody = $inline_object1;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2CaptureByOrder
     *
     * Capture amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject2 $inline_object2 inline_object2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Sezzle\InlineResponse2002|object[]|object[]|object[]|object[]
     */
    public function postV2CaptureByOrder($order_uuid, $sezzle_request_id = null, $inline_object2 = null)
    {
        [$response] = $this->postV2CaptureByOrderWithHttpInfo($order_uuid, $sezzle_request_id, $inline_object2);

        return $response;
    }

    /**
     * Operation postV2CaptureByOrderWithHttpInfo
     *
     * Capture amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject2 $inline_object2 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Sezzle\InlineResponse2002|object[]|object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2CaptureByOrderWithHttpInfo($order_uuid, $sezzle_request_id = null, $inline_object2 = null)
    {
        $request = $this->postV2CaptureByOrderRequest($order_uuid, $sezzle_request_id, $inline_object2);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if (\OpenAPI\Client\Sezzle\InlineResponse2002::class === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\InlineResponse2002::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                case 401:
                case 404:
                case 422:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\InlineResponse2002::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\InlineResponse2002::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2CaptureByOrderAsync
     *
     * Capture amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject2 $inline_object2 (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2CaptureByOrderAsync($order_uuid, $sezzle_request_id = null, $inline_object2 = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2CaptureByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id, $inline_object2)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2CaptureByOrderAsyncWithHttpInfo
     *
     * Capture amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject2 $inline_object2 (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2CaptureByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id = null, $inline_object2 = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\InlineResponse2002::class;
        $request = $this->postV2CaptureByOrderRequest($order_uuid, $sezzle_request_id, $inline_object2);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2CaptureByOrder'
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject2 $inline_object2 (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2CaptureByOrderRequest($order_uuid, $sezzle_request_id = null, $inline_object2 = null): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling postV2CaptureByOrder'
            );
        }

        $resourcePath = '/order/{order_uuid}/capture';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($sezzle_request_id !== null) {
            $headerParams['Sezzle-Request-Id'] = ObjectSerializer::toHeaderValue($sezzle_request_id);
        }

        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($inline_object2)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($inline_object2));
            } else {
                $httpBody = $inline_object2;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2ReauthorizeByOrder
     *
     * Reauthorize amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Reauthorize request (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return SessionStatus|object[]|object[]|object[]|object[]
     */
    public function postV2ReauthorizeByOrder($order_uuid, $sezzle_request_id = null, $price = null)
    {
        [$response] = $this->postV2ReauthorizeByOrderWithHttpInfo($order_uuid, $sezzle_request_id, $price);

        return $response;
    }

    /**
     * Operation postV2ReauthorizeByOrderWithHttpInfo
     *
     * Reauthorize amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Reauthorize request (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of SessionStatus|object[]|object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2ReauthorizeByOrderWithHttpInfo($order_uuid, $sezzle_request_id = null, $price = null)
    {
        $request = $this->postV2ReauthorizeByOrderRequest($order_uuid, $sezzle_request_id, $price);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('SessionStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\SessionStatus::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                case 401:
                case 404:
                case 422:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\SessionStatus::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\SessionStatus::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2ReauthorizeByOrderAsync
     *
     * Reauthorize amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Reauthorize request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2ReauthorizeByOrderAsync($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2ReauthorizeByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id, $price)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2ReauthorizeByOrderAsyncWithHttpInfo
     *
     * Reauthorize amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Reauthorize request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2ReauthorizeByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\SessionStatus::class;
        $request = $this->postV2ReauthorizeByOrderRequest($order_uuid, $sezzle_request_id, $price);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2ReauthorizeByOrder'
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Reauthorize request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2ReauthorizeByOrderRequest($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling postV2ReauthorizeByOrder'
            );
        }

        $resourcePath = '/order/{order_uuid}/reauthorize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($sezzle_request_id !== null) {
            $headerParams['Sezzle-Request-Id'] = ObjectSerializer::toHeaderValue($sezzle_request_id);
        }

        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($price)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($price));
            } else {
                $httpBody = $price;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2RefundByOrder
     *
     * Refund amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Refund request (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Sezzle\InlineResponse2002|object[]|object[]|object[]|object[]
     */
    public function postV2RefundByOrder($order_uuid, $sezzle_request_id = null, $price = null)
    {
        [$response] = $this->postV2RefundByOrderWithHttpInfo($order_uuid, $sezzle_request_id, $price);

        return $response;
    }

    /**
     * Operation postV2RefundByOrderWithHttpInfo
     *
     * Refund amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Refund request (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Sezzle\InlineResponse2002|object[]|object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2RefundByOrderWithHttpInfo($order_uuid, $sezzle_request_id = null, $price = null)
    {
        $request = $this->postV2RefundByOrderRequest($order_uuid, $sezzle_request_id, $price);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if (\OpenAPI\Client\Sezzle\InlineResponse2002::class === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\InlineResponse2002::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                case 401:
                case 404:
                case 422:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\InlineResponse2002::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\InlineResponse2002::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2RefundByOrderAsync
     *
     * Refund amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Refund request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2RefundByOrderAsync($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2RefundByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id, $price)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2RefundByOrderAsyncWithHttpInfo
     *
     * Refund amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Refund request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2RefundByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\InlineResponse2002::class;
        $request = $this->postV2RefundByOrderRequest($order_uuid, $sezzle_request_id, $price);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2RefundByOrder'
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Refund request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2RefundByOrderRequest($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling postV2RefundByOrder'
            );
        }

        $resourcePath = '/order/{order_uuid}/refund';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($sezzle_request_id !== null) {
            $headerParams['Sezzle-Request-Id'] = ObjectSerializer::toHeaderValue($sezzle_request_id);
        }

        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($price)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($price));
            } else {
                $httpBody = $price;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2ReleaseByOrder
     *
     * Release amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Release request (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Sezzle\InlineResponse2002|object[]|object[]|object[]|object[]
     */
    public function postV2ReleaseByOrder($order_uuid, $sezzle_request_id = null, $price = null)
    {
        [$response] = $this->postV2ReleaseByOrderWithHttpInfo($order_uuid, $sezzle_request_id, $price);

        return $response;
    }

    /**
     * Operation postV2ReleaseByOrderWithHttpInfo
     *
     * Release amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Release request (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Sezzle\InlineResponse2002|object[]|object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2ReleaseByOrderWithHttpInfo($order_uuid, $sezzle_request_id = null, $price = null)
    {
        $request = $this->postV2ReleaseByOrderRequest($order_uuid, $sezzle_request_id, $price);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if (\OpenAPI\Client\Sezzle\InlineResponse2002::class === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\InlineResponse2002::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                case 401:
                case 404:
                case 422:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\InlineResponse2002::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\InlineResponse2002::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2ReleaseByOrderAsync
     *
     * Release amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Release request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2ReleaseByOrderAsync($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2ReleaseByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id, $price)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2ReleaseByOrderAsyncWithHttpInfo
     *
     * Release amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Release request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2ReleaseByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\InlineResponse2002::class;
        $request = $this->postV2ReleaseByOrderRequest($order_uuid, $sezzle_request_id, $price);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2ReleaseByOrder'
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\Price $price Release request (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2ReleaseByOrderRequest($order_uuid, $sezzle_request_id = null, $price = null): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling postV2ReleaseByOrder'
            );
        }

        $resourcePath = '/order/{order_uuid}/release';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($sezzle_request_id !== null) {
            $headerParams['Sezzle-Request-Id'] = ObjectSerializer::toHeaderValue($sezzle_request_id);
        }

        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($price)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($price));
            } else {
                $httpBody = $price;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2UpchargeByOrder
     *
     * Upcharge amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject3 $inline_object3 inline_object3 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return SessionStatus|object[]|object[]|object[]|object[]
     */
    public function postV2UpchargeByOrder($order_uuid, $sezzle_request_id = null, $inline_object3 = null)
    {
        [$response] = $this->postV2UpchargeByOrderWithHttpInfo($order_uuid, $sezzle_request_id, $inline_object3);

        return $response;
    }

    /**
     * Operation postV2UpchargeByOrderWithHttpInfo
     *
     * Upcharge amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject3 $inline_object3 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of SessionStatus|object[]|object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2UpchargeByOrderWithHttpInfo($order_uuid, $sezzle_request_id = null, $inline_object3 = null)
    {
        $request = $this->postV2UpchargeByOrderRequest($order_uuid, $sezzle_request_id, $inline_object3);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('SessionStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\SessionStatus::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                case 401:
                case 404:
                case 422:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\SessionStatus::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\SessionStatus::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 400:
                case 401:
                case 404:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2UpchargeByOrderAsync
     *
     * Upcharge amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject3 $inline_object3 (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2UpchargeByOrderAsync($order_uuid, $sezzle_request_id = null, $inline_object3 = null): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2UpchargeByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id, $inline_object3)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2UpchargeByOrderAsyncWithHttpInfo
     *
     * Upcharge amount by order
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject3 $inline_object3 (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2UpchargeByOrderAsyncWithHttpInfo($order_uuid, $sezzle_request_id = null, $inline_object3 = null): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\SessionStatus::class;
        $request = $this->postV2UpchargeByOrderRequest($order_uuid, $sezzle_request_id, $inline_object3);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2UpchargeByOrder'
     *
     * @param  string $order_uuid Order UUID (required)
     * @param  string $sezzle_request_id Unique client-generated ID to enforce idempotency (optional)
     * @param  \OpenAPI\Client\Sezzle\InlineObject3 $inline_object3 (optional)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2UpchargeByOrderRequest($order_uuid, $sezzle_request_id = null, $inline_object3 = null): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'order_uuid' is set
        if ($order_uuid === null || (is_array($order_uuid) && $order_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_uuid when calling postV2UpchargeByOrder'
            );
        }

        $resourcePath = '/order/{order_uuid}/upcharge';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($sezzle_request_id !== null) {
            $headerParams['Sezzle-Request-Id'] = ObjectSerializer::toHeaderValue($sezzle_request_id);
        }

        // path params
        $resourcePath = str_replace(
            '{order_uuid}',
            ObjectSerializer::toPathValue($order_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($inline_object3)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($inline_object3));
            } else {
                $httpBody = $inline_object3;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
