<?php

/**
 * WebhooksApi
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sezzle API
 *
 * The Sezzle API is intended for merchants interested in accepting Sezzle Pay as a payment option.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Sezzle;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * WebhooksApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApi
{
    protected \GuzzleHttp\ClientInterface $client;

    protected \OpenAPI\Client\Configuration $config;

    protected \OpenAPI\Client\HeaderSelector $headerSelector;

    /**
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $configuration = null,
        HeaderSelector $headerSelector = null,
        protected $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $configuration ?: new Configuration();
        $this->headerSelector = $headerSelector ?: new HeaderSelector();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    public function getConfig(): \OpenAPI\Client\Configuration
    {
        return $this->config;
    }

    /**
     * Operation deleteV2Webhooks
     *
     * Delete webhooks
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function deleteV2Webhooks($webhooks_uuid): void
    {
        $this->deleteV2WebhooksWithHttpInfo($webhooks_uuid);
    }

    /**
     * Operation deleteV2WebhooksWithHttpInfo
     *
     * Delete webhooks
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteV2WebhooksWithHttpInfo($webhooks_uuid): array
    {
        $request = $this->deleteV2WebhooksRequest($webhooks_uuid);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 400:
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation deleteV2WebhooksAsync
     *
     * Delete webhooks
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function deleteV2WebhooksAsync($webhooks_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->deleteV2WebhooksAsyncWithHttpInfo($webhooks_uuid)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation deleteV2WebhooksAsyncWithHttpInfo
     *
     * Delete webhooks
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function deleteV2WebhooksAsyncWithHttpInfo($webhooks_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        $request = $this->deleteV2WebhooksRequest($webhooks_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                fn ($response): array => [null, $response->getStatusCode(), $response->getHeaders()],
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteV2Webhooks'
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function deleteV2WebhooksRequest($webhooks_uuid): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'webhooks_uuid' is set
        if ($webhooks_uuid === null || (is_array($webhooks_uuid) && $webhooks_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $webhooks_uuid when calling deleteV2Webhooks'
            );
        }

        $resourcePath = '/webhooks/{webhooks_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{webhooks_uuid}',
            ObjectSerializer::toPathValue($webhooks_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getV2Webhook
     *
     * get webhook
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|object[]|object[]
     */
    public function getV2Webhook($webhooks_uuid)
    {
        [$response] = $this->getV2WebhookWithHttpInfo($webhooks_uuid);

        return $response;
    }

    /**
     * Operation getV2WebhookWithHttpInfo
     *
     * get webhook
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getV2WebhookWithHttpInfo($webhooks_uuid)
    {
        $request = $this->getV2WebhookRequest($webhooks_uuid);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                case 404:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 401:
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation getV2WebhookAsync
     *
     * get webhook
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getV2WebhookAsync($webhooks_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->getV2WebhookAsyncWithHttpInfo($webhooks_uuid)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation getV2WebhookAsyncWithHttpInfo
     *
     * get webhook
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getV2WebhookAsyncWithHttpInfo($webhooks_uuid): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = 'object';
        $request = $this->getV2WebhookRequest($webhooks_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getV2Webhook'
     *
     * @param  string $webhooks_uuid Webhooks UUID (required)
     *
     * @throws \InvalidArgumentException
     */
    public function getV2WebhookRequest($webhooks_uuid): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'webhooks_uuid' is set
        if ($webhooks_uuid === null || (is_array($webhooks_uuid) && $webhooks_uuid === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $webhooks_uuid when calling getV2Webhook'
            );
        }

        $resourcePath = '/webhooks/{webhooks_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{webhooks_uuid}',
            ObjectSerializer::toPathValue($webhooks_uuid),
            $resourcePath
        );


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getV2Webhooks
     *
     * List webhooks
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object[]|object[]|object[]
     */
    public function getV2Webhooks()
    {
        [$response] = $this->getV2WebhooksWithHttpInfo();

        return $response;
    }

    /**
     * Operation getV2WebhooksWithHttpInfo
     *
     * List webhooks
     *
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getV2WebhooksWithHttpInfo()
    {
        $request = $this->getV2WebhooksRequest();

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                case 400:
                case 401:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = 'object[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                case 400:
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation getV2WebhooksAsync
     *
     * List webhooks
     *
     *
     * @throws \InvalidArgumentException
     */
    public function getV2WebhooksAsync(): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->getV2WebhooksAsyncWithHttpInfo()
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation getV2WebhooksAsyncWithHttpInfo
     *
     * List webhooks
     *
     *
     * @throws \InvalidArgumentException
     */
    public function getV2WebhooksAsyncWithHttpInfo(): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = 'object[]';
        $request = $this->getV2WebhooksRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getV2Webhooks'
     *
     *
     * @throws \InvalidArgumentException
     */
    public function getV2WebhooksRequest(): \GuzzleHttp\Psr7\Request
    {

        $resourcePath = '/webhooks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2WebhookTest
     *
     * Trigger a test webhook
     *
     * @param  \OpenAPI\Client\Sezzle\WebhookTest $webhook_test request (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function postV2WebhookTest($webhook_test): void
    {
        $this->postV2WebhookTestWithHttpInfo($webhook_test);
    }

    /**
     * Operation postV2WebhookTestWithHttpInfo
     *
     * Trigger a test webhook
     *
     * @param  \OpenAPI\Client\Sezzle\WebhookTest $webhook_test request (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2WebhookTestWithHttpInfo($webhook_test): array
    {
        $request = $this->postV2WebhookTestRequest($webhook_test);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 400:
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2WebhookTestAsync
     *
     * Trigger a test webhook
     *
     * @param  \OpenAPI\Client\Sezzle\WebhookTest $webhook_test request (required)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2WebhookTestAsync($webhook_test): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2WebhookTestAsyncWithHttpInfo($webhook_test)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2WebhookTestAsyncWithHttpInfo
     *
     * Trigger a test webhook
     *
     * @param  \OpenAPI\Client\Sezzle\WebhookTest $webhook_test request (required)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2WebhookTestAsyncWithHttpInfo($webhook_test): \GuzzleHttp\Promise\PromiseInterface
    {
        $request = $this->postV2WebhookTestRequest($webhook_test);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                fn ($response): array => [null, $response->getStatusCode(), $response->getHeaders()],
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2WebhookTest'
     *
     * @param  \OpenAPI\Client\Sezzle\WebhookTest $webhook_test request (required)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2WebhookTestRequest($webhook_test): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'webhook_test' is set
        if ($webhook_test === null || (is_array($webhook_test) && $webhook_test === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $webhook_test when calling postV2WebhookTest'
            );
        }

        $resourcePath = '/webhooks/test';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($webhook_test)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($webhook_test));
            } else {
                $httpBody = $webhook_test;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postV2Webhooks
     *
     * Create webhooks
     *
     * @param  \OpenAPI\Client\Sezzle\Webhook $webhook Webhooks request (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Sezzle\InlineResponse2003|object[]|object[]|object[]
     */
    public function postV2Webhooks($webhook)
    {
        [$response] = $this->postV2WebhooksWithHttpInfo($webhook);

        return $response;
    }

    /**
     * Operation postV2WebhooksWithHttpInfo
     *
     * Create webhooks
     *
     * @param  \OpenAPI\Client\Sezzle\Webhook $webhook Webhooks request (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Sezzle\InlineResponse2003|object[]|object[]|object[], HTTP status code, HTTP response headers (array of strings)
     */
    public function postV2WebhooksWithHttpInfo($webhook)
    {
        $request = $this->postV2WebhooksRequest($webhook);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() instanceof \Psr\Http\Message\ResponseInterface ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if (\OpenAPI\Client\Sezzle\InlineResponse2003::class === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, \OpenAPI\Client\Sezzle\InlineResponse2003::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                case 401:
                case 422:
                    if ('object[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = \OpenAPI\Client\Sezzle\InlineResponse2003::class;
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \OpenAPI\Client\Sezzle\InlineResponse2003::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
                case 400:
                case 401:
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'object[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);

                    break;
            }

            throw $apiException;
        }
    }

    /**
     * Operation postV2WebhooksAsync
     *
     * Create webhooks
     *
     * @param  \OpenAPI\Client\Sezzle\Webhook $webhook Webhooks request (required)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2WebhooksAsync($webhook): \GuzzleHttp\Promise\PromiseInterface
    {
        return $this->postV2WebhooksAsyncWithHttpInfo($webhook)
            ->then(
                fn ($response) => $response[0]
            );
    }

    /**
     * Operation postV2WebhooksAsyncWithHttpInfo
     *
     * Create webhooks
     *
     * @param  \OpenAPI\Client\Sezzle\Webhook $webhook Webhooks request (required)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2WebhooksAsyncWithHttpInfo($webhook): \GuzzleHttp\Promise\PromiseInterface
    {
        $returnType = \OpenAPI\Client\Sezzle\InlineResponse2003::class;
        $request = $this->postV2WebhooksRequest($webhook);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType): array {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postV2Webhooks'
     *
     * @param  \OpenAPI\Client\Sezzle\Webhook $webhook Webhooks request (required)
     *
     * @throws \InvalidArgumentException
     */
    public function postV2WebhooksRequest($webhook): \GuzzleHttp\Psr7\Request
    {
        // verify the required parameter 'webhook' is set
        if ($webhook === null || (is_array($webhook) && $webhook === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $webhook when calling postV2Webhooks'
            );
        }

        $resourcePath = '/webhooks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($webhook)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($webhook));
            } else {
                $httpBody = $webhook;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query !== '' && $query !== '0' ? '?' . $query : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
