name: PHPStan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse lib
